dist: xenial
language: python
python:
  - "3.7"
cache: pip
install:
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls
script:
  - python test_gradient_button.py
after_success:
  - coveralls

