dist: xenial
language: python
python:
  - "2.7"
  - "3.5"
  - "3.7"
- sudo python -m easy_install pyyaml
coverage run --source=tkGradientButton test_gradient_button.py test
after_success:
  - coveralls

